### PR TITLE
Testing Tic-tac 

### PR DESCRIPTION
**Pull request by CollinsTatang**
Test created for the player, board, and table classes 
Player
 - check that the player can be created with the name and the symbol
 Board
 - check that the board that is created containing the square of cell
 - check victory method in accordance with all the condition
 - Test the draw method
Table
- Test that the table is printed correctly to reflect the data in the square

### CODE REVIEW

**Comment by mimipeshy** [comment]
### STATUS: CHANGES REQUESTED 🔴 ♻️ 

Hello team @CollinsTatang and @erezfree29 👋🏾 👋🏾 , I commend the effort you have put into this milestone.
✔️  Great job in writing a proper description 👏🏾 👏🏾 
✔️ Great job in writing the tests I enjoyed running them
However before the project can be marked as complete, check out the following

- [ ] For someone to run your tests, they need to install `terminal-table`, update your README file to reflect how a person can run your tests, don't forget to add the above requirement 😄 

That's all :smile: kindly submit another review when done.

_Feel free to reach out to me on slack if you have any questions or something is unclear, or just comment on this PR and tag my name and I will be glad to help_
Regards
Peris Ndanu

**Comment by mimipeshy** [comment]
### STATUS : CHANGES REQUIRED 🔴 ♻️ 
Hello there @CollinsTatang 👋🏾 👋🏾 , I commend the effort you have made in this milestone. However, something is still missing in the README file

- [ ] `_- TEST In order to run the test on the table.rb file the user needs to install rspec in the project and used the rspec --fileName command on the terminal.`  This statement works for users who have installed `terminal-table` locally.  
For someone who has not, they will have an issue running your tests. You need to add it to the instructions
 ` After installing RSpec, run gem install terminal-table`. 
`To run the tests just type rspec` 

That way all users can run your tests without any issue.

Kindly fix that and submit it for another review.

_Feel free to reach out to me on slack if you have any questions or something is unclear, or just comment on this PR and tag my name and I will be glad to help_
Regards
Peris Ndanu

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGES REQUIRED :red_circle: :recycle: 
-------------
Hello @CollinsTatang @erezfree29 :wave: You are doing an excellent job on this project :muscle: :100: 
There are a few changes to make to complete this project :hammer_and_wrench: see them below :eyes: :point_down: 
---------------

- [ ] Don't change the original rubocop original file. Please use the original file. 

linter_config

- [ ] Improve your commit messages. Remember that the commit should be in the imperative [here](https://github.com/trein/dev-best-practices/wiki/Git-Commit-Best-Practices#formatting-rules) you can check the rules of a good commit message. [Here](https://docs.github.com/en/github/committing-changes-to-your-project/changing-a-commit-message) you can read how to change a commit message. You don't need to changes these commit messages this time but keep the formatting rules in mind for the next projects. 
- [ ] Please add negative scenarios for the RSpec. E.g `check that the method returns false when condition four is not met ().not_to be true`.
---------------- 
Make these required changes :hammer_and_wrench:  and send it for another review :+1: :smile: 
HAPPY CODING!!

AngelicConcreteHypsilophodon-max-1mb

**Review by cyonii — APPROVED** [review]
# Status: Approved 👏

Hello team, good job implementing all the requested changes.
You can now merge your PR and carry on.

Happy coding 👏🤓


## OPTIONAL SUGGESTIONS
Note that these are optional suggestions, which means you are not obliged to do them, but I encourage you to implement them.

- [ ] If you have any dependent gem that needs to be installed, you should put them in a `Gemfile` so that users can easily install the necessary gems by running `bundle install`, e.g the `terminal-table` gem.
- [ ] Cover codes in backticks (`) so that they're clearer to the reader

### You can find me on slack 👉 [CY Kalu](https://microverse-students.slack.com/team/U01494U96FR) if you need further assistance or clarification. I'm always available and will be glad to help.

**Pull request merged**
